print("Molly Depew")
print("I am a second year Computer Science major")
print("I am from a small town called Marblehead in Massachusetts")
print("I am two older sisters")
print("I like to play hockey")
